# dynmap-mobs configuration
#
update:
  # Seconds between position updates for mobs
  period: 5.0
  # Seconds between position updates for vehicles
  vehicleperiod: 10.0
  # Round position to given unit
  resolution: 1.0
  # Make markers hidden when they are inside/underground/in shadows (#=light level: 0=full shadow,15=sky(disable hide))
  hideifshadow: 4
  # Make markers hidden when they are under cover (#=sky light level,0=underground,15=open to sky(disable hide))
  hideifundercover: 15
  # Mob updates per tick (prevent lag spikes when large number of mobs)
  mobs-per-tick: 20
  # Vehicle updates per tick (prevent lag spikes when large number of vehicles)
  vehicles-per-tick: 20

mobs:
  # Include creepers
  creeper: true
  # Include skeletons
  skeleton: true
  # Include zombies
  zombie: true
  # Include blazes
  blaze: true
  # Include ghasts
  ghast: true
  # Include silverfish
  silverfish: true
  # Include slimes
  slime: true
  # Include spiders
  spider: true
  # Include wolves
  wolf: true
  # Include zombie-pigmen
  zombiepigman: true
  # Include Enderdragon
  enderdragon: true
  # Include snow golems
  snowgolem: true
  # Include cave spider
  cavespider: true
  # Include spider jockey
  spiderjockey: true
  # Include enderman
  enderman: true
  # Include cows
  cow: false
  # Include pigs
  pig: false
  # Include chickens
  chicken: false
  # Include squids
  squid: false
  # Include sheep
  sheep: false
  # Include villagers
  villager: false
  # Include mooshroom
  mooshroom: false
  # Include tamed wolves
  tamedwolf: true  
  # Include ocelots
  ocelot: true
  # Include tamed cats
  cat: true
  # Include Iron golems
  golem: true
  # Include witches
  witch: true
  # Include wither skeletons
  witherskeleton: true
  # Include wither
  wither: true
  # Include zombie villager
  zombievillager: true
  # Include bats
  bat: false
  # Include horses (vanilla MC)
  vanillahorse: false
  # Include rabbits
  rabbit: false
  # Include endermites
  endermite: true
  # Include magma cube
  magmacube: true
  # Include guardian
  guardian: true
  # Include shulker
  shulker: true
  # Include polarbear
  polarbear: false
  # Include evoker
  evoker: true
  # Include vex
  vex: true
  # Include vindicator
  vindicator: true
  # Include llama
  llama: false

vehicles:
  # Specific minecart types
  explosive-minecart: false
  hopper-minecart: false
  powered-minecart: false
  spawner-minecart: false
  storage-minecart: false
  minecart: false
  # Boats
  boat: false
  
layer:
  name: "Mobs"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 10
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false
  
vehiclelayer:
  name: "Vehicles"
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 11
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false
  